version: '3.3'
services:  
  php7.4:
    build: ../dockerfile/php-7.4.16
    tty: true
    restart: always
    container_name: php7.4
    volumes:
      - /data/www:/var/www/html
      - /data/logs/php74:/var/log/php
      - /data/docker/config/php74/php.ini:/usr/local/etc/php/php.ini
      - /data/docker/config/php74/www.conf:/usr/local/etc/php-fpm.d/www.conf